name: vercel_edge
description: Write and deploy Dart functions to the Vercel Edge network.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/cloudflare_workers
version: 0.0.3+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.5
  edge_runtime: ^0.0.3
  js_bindings:
    git:
      url: git@github.com:jodinathan/js_bindings.git
      ref: adc8f2fbb794b86af7280f2aa5adb2b48cdefa43
  js: ^0.6.5
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
