name: supabase_functions
description: Write and deploy Dart functions to Supabase Functions.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/supabase_functions
version: 0.0.1-dev.3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  deno_deploy: ^0.0.1-dev.2
  edge: ^0.0.5
  edge_runtime: ^0.0.3
  js_bindings:
    git:
      url: git@github.com:jodinathan/js_bindings.git
      ref: adc8f2fbb794b86af7280f2aa5adb2b48cdefa43
  js: ^0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
